### This is a simple notebook used to model a linear relationship with ML algorithms.

It accompanies Chapter 1 of the book, but it is only used to derive the numbers quoted in the text.

Author: Viviana Acquaviva

License: TBD

In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
font = {'size'   : 16}
matplotlib.rc('font', **font)
matplotlib.rc('xtick', labelsize=14) 
matplotlib.rc('ytick', labelsize=14) 
#matplotlib.rcParams.update({'figure.autolayout': True})
#matplotlib.rcParams['figure.dpi'] = 300

In [3]:
np.random.seed(16) #set seed for reproducibility purposes
x = np.arange(10) 
y = 2*x + 5 + np.random.randn(10) #generate some data with random gaussian scatter

In [ ]:
plt.figure(figsize=(8,6))
plt.scatter(x,y, c = 'red')
plt.xlabel('time (s)')
plt.ylabel('distance (m)')

In [5]:
print(x,np.round(y,1))

[0 1 2 3 4 5 6 7 8 9] [ 5.1  5.5  8.4 11.1 11.8 14.4 16.1 19.5 20.2 23.1]


In [6]:
y = np.round(y,1)

#### Let's import a couple of simple machine learning models 

In [7]:
from sklearn.tree import DecisionTreeRegressor

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
from sklearn.model_selection import train_test_split 

In [10]:
np.random.seed(10) #fix for reproducibility

X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=3) #create train/test split

In [11]:
X_train, y_train

(array([6, 3, 1, 0, 7, 4, 9]),
 array([16.1, 11.1,  5.5,  5.1, 19.5, 11.8, 23.1]))

In [12]:
X_test

array([8, 2, 5])

In [13]:
treemodel = DecisionTreeRegressor() # default params

In [14]:
regmodel = LinearRegression() # default params

Build the model on the training set and use it to predict the output for the test set!

In [15]:
y_pred_tree = treemodel.fit(X_train.reshape(-1, 1), y_train).predict(X_test.reshape(-1, 1))

In [16]:
y_pred_reg = regmodel.fit(X_train.reshape(-1, 1), y_train).predict(X_test.reshape(-1, 1))

In [17]:
y_test, y_pred_reg, y_pred_tree #True/predicted by LR and DT respectively

(array([20.2,  8.4, 14.4]),
 array([20.89279279,  8.41981982, 14.65630631]),
 array([19.5,  5.5, 11.8]))

Calculate Mean Squared Error for the two models

In [18]:
np.mean((y_test-y_pred_reg)**2)

0.18201586721857252

In [19]:
np.mean((y_test-y_pred_tree)**2)

5.22

Predict the value at t = 12 s with the two models

In [20]:
print(treemodel.predict(np.array(12).reshape(-1, 1)))
print(regmodel.predict(np.array(12).reshape(-1, 1)))

[23.1]
[29.20810811]


Solution to exercise 8

In [21]:
regmodel.fit(x.reshape(-1, 1), y)
print(regmodel.predict(np.array(12).reshape(-1, 1)))

[28.88363636]
